// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ2PPehPdYGscmVhIpbkEMCauZ09SISeU',
    appId: '1:229842300141:web:17ce59020a58ff17abb0e4',
    messagingSenderId: '229842300141',
    projectId: 'cs8803-sampleapp2',
    authDomain: 'cs8803-sampleapp2.firebaseapp.com',
    storageBucket: 'cs8803-sampleapp2.firebasestorage.app',
    measurementId: 'G-BMQTGL0MV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVEzBuabU4eTYjCi17zDx5YMMgqTlJF4',
    appId: '1:229842300141:android:e8262c5cec525616abb0e4',
    messagingSenderId: '229842300141',
    projectId: 'cs8803-sampleapp2',
    storageBucket: 'cs8803-sampleapp2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0WE3wDXgGm8TgJPG2mSS4KS5fGpMixhU',
    appId: '1:229842300141:ios:b88e92b94d69d609abb0e4',
    messagingSenderId: '229842300141',
    projectId: 'cs8803-sampleapp2',
    storageBucket: 'cs8803-sampleapp2.firebasestorage.app',
    iosBundleId: 'com.faizaapp.sampleapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0WE3wDXgGm8TgJPG2mSS4KS5fGpMixhU',
    appId: '1:229842300141:ios:d56f158c244ae3aeabb0e4',
    messagingSenderId: '229842300141',
    projectId: 'cs8803-sampleapp2',
    storageBucket: 'cs8803-sampleapp2.firebasestorage.app',
    iosBundleId: 'com.example.samppleApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ2PPehPdYGscmVhIpbkEMCauZ09SISeU',
    appId: '1:229842300141:web:73b5cb707a928d65abb0e4',
    messagingSenderId: '229842300141',
    projectId: 'cs8803-sampleapp2',
    authDomain: 'cs8803-sampleapp2.firebaseapp.com',
    storageBucket: 'cs8803-sampleapp2.firebasestorage.app',
    measurementId: 'G-EJGS80CLS1',
  );
}
